version: "2.2"
services:
  image-and-words:
    build: ./
    ports:
        - "8080:80"
    hostname: image-and-words
    # CPU/mem resources
    cpus: 2
    mem_limit: 2048M
    memswap_limit: 0M
    mem_reservation: 1024M
    shm_size: 32M
    # core - limits the core file size (KB)
    # data - max data size (KB)
    # fsize - maximum filesize (bytes)
    # memlock - max locked-in-memory address space (KB)
    # nofile - max number of open file descriptors
    # rss - max resident set size (KB), https://stackoverflow.com/a/3361037
    # stack - max stack size (KB)
    # cpu - max CPU time (MIN)
    # nproc - max number of processes
    # as - address space limit (KB)
    # maxlogins - max number of logins for this user
    # maxsyslogins - max number of logins on the system
    # priority - the priority to run user process with
    # locks - max number of file locks the user can hold
    # sigpending - max number of pending signals
    # msgqueue - max memory used by POSIX message queues (bytes)
    # nice - max nice priority allowed to raise to values: [-20, 19]
    # rtprio - max realtime priority
    ulimits:
      #core: 0
      fsize: 128000000 # 128 MB
      #nofile: 32768
      #as: # NOTE: this is address space. Lots of program will crash if you limit this
      nproc: 4096
      nice: 0
