version: "3"
services:
  nginx:
    image: nginx:alpine
    user: nginx:nginx
    entrypoint: nginx
    container_name: nginx
    ports:
      - "80:8080/tcp"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
